logo: /assets/img/logo.png
show_downloads: true
theme: jekyll-theme-minimal
github:
  zip_url: https://github.com/CODRA-Ingenierie-Informatique/CodraFT/releases
  tar_url: https://github.com/CODRA-Ingenierie-Informatique/CodraFT/releases
